// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plhdfjztuzeucphpxomr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaGRmanp0dXpldWNwaHB4b21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzk1ODAsImV4cCI6MjA2MDgxNTU4MH0.vkves8-AEkgQUlmktR4pW-z49ESmIEjsxqhK43VXD2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);