// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwgejtonllfivubtngfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Z2VqdG9ubGxmaXZ1YnRuZ2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzMxNTQsImV4cCI6MjA2MDcwOTE1NH0.2ZYIVscN3ONLx0iK-xeJwoST7RcqAg2LVjwtKxblPFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);